// <auto-generated />
namespace BookManagementPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Vinh120320191 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vinh120320191));
        
        string IMigrationMetadata.Id
        {
            get { return "201903111712338_Vinh120320191"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
